import os

Import('qt_env')

env = qt_env.Clone()

env.EnableQtModules('Widgets')

env.AppendUnique(CPPPATH = [
    os.path.join('..', 'gamefeatures'),
    '${BOOSTPATH}'
])

#env.AppendUnique(LIBS = [
#        'advapi32',
#        'ole32',
#        'shell32',
#        'version'
#])

lib = env.StaticLibrary('gameGamebryo', env.Glob('*.cpp'))
#env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
